Cloud bastion
Otus-DevOps-2020-11/UsedC_infra pull request #3
Opened 2020-12-20 13:37 UTC by UsedC

# Выполнено ДЗ №

 - [ * ] Основное ДЗ
 - [ * ] Задание со * №1 (Алиас)
 - [ - ] Задание со * №2 (Сертификат)

## В процессе сделано:
 - Созданы 2 виртуальные машины
 - Создан VPN

## Как запустить проект:
 - Использовать конфигурационный файл cloud-bastion.ovpn для покдлючения к VPN (openvpn --config cloud-bastion.ovpn)

## Как проверить работоспособность:
 - Попробовать подключиться по ssh ко внутреннему ресурсу, указанному в README

## PR checklist
 - [ * ] Выставил label с номером домашнего задания
 - [ * ] Выставил label с темой домашнего задания

2020-12-21 13:35 UTC, mrgreyves requested changes
Здравствуйте! Оставил комментарий к файлу, постарайтесь пофиксить. ДЗ возвращаю на доработку.

2020-12-21 13:35 UTC, mrgreyves commented on README.md
> +Конфигурация для подключения:
Попробуйте удалить строчку "Конфигурация подкючения" тревис не может распарсить данные (

2020-12-22 10:37 UTC, UsedC commented on README.md
> +Конфигурация для подключения:
Не помогло

2020-12-23 13:42 UTC, mrgreyves approved these changes
Здравствуйте!) Штош, проверю в ручную. Дз корректно, принимаю!=)

2020-12-23 13:47 UTC, merged